services:
  jwt_test_postgres_db:
    image: postgres:16.4-alpine3.20
    restart: no
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root